import type { SvgAssetDefinition, SvgAssetCategory } from "./editorTypes";

export const svgAssetCategoryLabels: Record<SvgAssetCategory, string> = {
  corners: "Colțuri",
  flowers: "Flori",
  geometric: "Geometric",
};

export const editorSvgAssets: SvgAssetDefinition[] = [
  {
    id: "corner-01",
    name: "Colț ornamental 01",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-1.svg",
    naturalWidth: 589.22,
    naturalHeight: 587.5,
    defaultWidthRatio: 0.16,
  },
  {
    id: "corner-02",
    name: "Colț ornamental 02",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-2.svg",
    naturalWidth: 416.24,
    naturalHeight: 417.2,
    defaultWidthRatio: 0.16,
  },
  {
    id: "corner-03",
    name: "Colț ornamental 03",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-3.svg",
    naturalWidth: 273.35,
    naturalHeight: 273.35,
    defaultWidthRatio: 0.15,
  },
  {
    id: "corner-04",
    name: "Colț ornamental 04",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-4.svg",
    naturalWidth: 606.22,
    naturalHeight: 607.05,
    defaultWidthRatio: 0.16,
  },
  {
    id: "corner-05",
    name: "Colț ornamental 05",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-5.svg",
    naturalWidth: 365.57,
    naturalHeight: 373.08,
    defaultWidthRatio: 0.16,
  },
  {
    id: "corner-06",
    name: "Colț ornamental 06",
    category: "corners",
    src: "/editorsvgfiles/corners/Untitled-6.svg",
    naturalWidth: 324.52,
    naturalHeight: 323.18,
    defaultWidthRatio: 0.16,
  },
  {
    id: "flower-01",
    name: "Floare verticală 01",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f1.svg",
    naturalWidth: 560.72,
    naturalHeight: 792.48,
    defaultWidthRatio: 0.14,
  },
  {
    id: "flower-02",
    name: "Floare verticală 02",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f2.svg",
    naturalWidth: 318.88,
    naturalHeight: 572.42,
    defaultWidthRatio: 0.12,
  },
  {
    id: "flower-03",
    name: "Floare rotundă",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f3.svg",
    naturalWidth: 530.61,
    naturalHeight: 549.15,
    defaultWidthRatio: 0.16,
  },
  {
    id: "flower-04",
    name: "Bordură florală",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f4.svg",
    naturalWidth: 814.14,
    naturalHeight: 195.55,
    defaultWidthRatio: 0.24,
  },
  {
    id: "flower-05",
    name: "Floare compusă",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f5.svg",
    naturalWidth: 189.93,
    naturalHeight: 382.18,
    defaultWidthRatio: 0.12,
  },
  {
    id: "flower-06",
    name: "Tijă florală",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f6.svg",
    naturalWidth: 317.45,
    naturalHeight: 582,
    defaultWidthRatio: 0.12,
  },
  {
    id: "flower-07",
    name: "Lalea ornamentală",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f7.svg",
    naturalWidth: 93.25,
    naturalHeight: 277.4,
    defaultWidthRatio: 0.11,
  },
  {
    id: "flower-08",
    name: "Ramură florală",
    category: "flowers",
    src: "/editorsvgfiles/flowers/Untitled-f8.svg",
    naturalWidth: 205.65,
    naturalHeight: 471.75,
    defaultWidthRatio: 0.13,
  },
  {
    id: "geometric-01",
    name: "Cadru geometric",
    category: "geometric",
    src: "/editorsvgfiles/shapes/Untitled-s1.svg",
    naturalWidth: 328.52,
    naturalHeight: 328.52,
    defaultWidthRatio: 0.2,
  },
  {
    id: "geometric-02",
    name: "Sigiliu geometric",
    category: "geometric",
    src: "/editorsvgfiles/shapes/Untitled-s2.svg",
    naturalWidth: 226.72,
    naturalHeight: 226.72,
    defaultWidthRatio: 0.2,
  },
  {
    id: "geometric-03",
    name: "Stea geometrică",
    category: "geometric",
    src: "/editorsvgfiles/shapes/Untitled-s3.svg",
    naturalWidth: 664.66,
    naturalHeight: 632.13,
    defaultWidthRatio: 0.22,
  },
];

export const editorAssetMap = Object.fromEntries(
  editorSvgAssets.map((asset) => [asset.id, asset])
) as Record<string, SvgAssetDefinition>;
